apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: myapp
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

